package com.yaozhetao.treebud.mapper;

import com.yaozhetao.treebud.model.TbUserinfo;
import com.yaozhetao.treebud.model.TbUserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int countByExample(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int deleteByExample(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int insert(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int insertSelective(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    List<TbUserinfo> selectByExampleWithBLOBs(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    List<TbUserinfo> selectByExample(TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    TbUserinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbUserinfo record, @Param("example") TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbUserinfo record, @Param("example") TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbUserinfo record, @Param("example") TbUserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(TbUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_userinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbUserinfo record);
}